name: app_servis
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  web: ^0.1.4-beta
  async: ^2.11.0
  shared_preferences: ^2.2.2
  # rflutter_alert: ^2.0.7
  video_player: ^2.8.1
  # progress_dialog_null_safe: ^1.0.7
  
  fluttertoast: ^8.2.2
  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  bloc: ^8.1.2
  firebase_database: ^10.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # assets:
  # - lib/assets/
  # - assets/videos/bg.mp4
