name: app_servis
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  animated_text_kit: ^4.2.2
  async: ^2.11.0
  bloc: ^8.1.2
  chewie: ^1.7.1
  cloud_firestore: ^4.12.2
  cloud_functions: ^4.5.4
  cupertino_icons: ^1.0.6
  drop_down_search_field: ^1.0.0
  firebase_auth: ^4.12.1
  firebase_core: ^2.21.0
  firebase_database: ^10.3.3
  firebase_storage: ^11.4.1
  flutter_datetime_picker: ^1.5.1
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.3.5
  fluttertoast: ^8.2.2
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.6
  http: ^1.1.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  loading_overlay: ^0.3.0
  rflutter_alert: ^2.0.7
  search_dropdown: ^0.0.2
  shared_preferences: ^2.2.2
  web: ^0.3.0
  flare_flutter: ^3.0.2
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf

  assets:
    - assets/images/
    - assets/videos/
