name: app_servis
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  web: ^0.1.4-beta
  async: ^2.11.0
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.2
  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  firebase_database: ^10.3.3
  firebase_storage: ^11.4.1
  cloud_firestore: ^4.12.2
  bloc: ^8.1.2
  image_picker: ^1.0.4
  animated_text_kit: ^4.2.2
  loading_overlay: ^0.3.0
  google_fonts: ^6.1.0
  flutter_native_splash: ^2.3.5
  cloud_functions: ^4.5.4
  flutter_datetime_picker: ^1.5.1
  intl: ^0.18.1
  search_dropdown: ^0.0.2
  drop_down_search_field: ^1.0.0
  chewie: ^1.7.1
  google_sign_in: ^6.1.6
  rflutter_alert: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family:  MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
        
  assets:
    - assets/images/
    - assets/videos/
