name: app_servis
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  animated_text_kit: ^4.2.2
  async: ^2.11.0
  bloc: ^8.1.2
  chewie: ^1.7.4
  cloud_firestore: ^4.13.4
  cloud_functions: ^4.5.7
  cupertino_icons: ^1.0.6
  drop_down_search_field: ^1.0.0
  firebase_auth: ^4.15.1
  firebase_core: ^2.24.1
  firebase_database: ^10.3.7
  firebase_storage: ^11.5.4
  flutter_datetime_picker: ^1.5.1
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.3.7
  fluttertoast: ^8.2.4
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.6
  http: ^1.1.2
  image_picker: ^1.0.4
  intl: ^0.19.0
  loading_overlay: ^0.3.0
  rflutter_alert: ^2.0.7
  search_dropdown: ^0.0.2
  shared_preferences: ^2.2.2
  web: ^0.3.0
  flare_flutter: ^3.0.2
  lottie: ^2.7.0
  firebase_analytics: ^10.7.3
  cached_network_image: ^3.3.0
  progress_dialog:
    git:
      url: https://github.com/mostafaAbdelazim/progress_dialog.git
  file_picker: ^6.1.1
  flutter_bloc: ^8.1.3
  flutter_facebook_auth: ^6.0.3
  image_picker_web: ^3.1.1
  flutter_rating_bar: ^4.0.1
  animated_splash_screen: ^1.3.0
  page_transition: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf

  assets:
    - assets/
    - assets/images/
    - assets/images/booking/
    - assets/videos/
