// ignore_for_file: non_constant_identifier_names

class ListKendaraan {
  final List<String> jenisKendaraan = ['Mobil', 'Sepeda Motor'];
  Map<String, List<String>> PerusahaanOptions = {
    'Mobil': [
      'Hyundai',
      'Toyota',
      'Daihatsu',
      'Honda Car',
      'Mitsubishi',
      'Wuling',
      'Lamborghini',
      'Ferrari',
      'Mazda',
      'BMW',
      'Volkswagen',
      'Jeep',
      'Audi',
      'Ford',
      'Peugeot',
      'Nissan',
      'Volvo',
      'Lexus',
      'Isuzu',
      'Suzuki Car',
      'Mercedes-Benz',
      'Mini',
      'Renault',
      'Tesla',
      'Jaguar',
      'KIA'
    ],
    'Sepeda Motor': [
      'Honda',
      'Yamaha',
      'Suzuki',
      'Kawasaki',
      'TVS Motor',
      'Viar',
      'Benelli',
      'KTM',
    ],
  };

  Map<String, List<String>> MerekOptions = {
    // MOBIL,MOBIL,MOBIL,MOBIL,MOBIL,MOBIL,MOBIL,MOBIL,MOBIL,MOBIL,MOBIL
    'Hyundai': [
      'Palisade',
      'Creta',
      'Santa Fe',
      'Ioniq',
      'Stargazer',
      'Staria',
      'Stargazer X',
    ],
    'Toyota': [
      'Alphard',
      'Kijang Innova',
      'Voxy',
      'Avanza',
      'Veloz',
      'Calya',
    ],
    'Daihatsu': [
      'Rocky',
      'Terios',
      'Sirion',
      'Luxio',
      'Ayla',
      'Granmax',
      'Xenia',
      'Sigra',
    ],
    'Honda Car': [
      'WR-V',
      'BR-V',
      'Brio',
      'Accord',
      'City',
      'Mobilio',
      'HR-V',
      'CR-V',
      'Civic',
    ],
    'Mitsubishi': [
      'Xpander',
      'Xpander Cross',
      'Pajero Sport',
      'XForce',
      'Outlander',
      'L300',
      'Triton',
    ],
    'Wuling': [
      'Formo',
      'Confero',
      'Confero S',
      'Cortez',
      'Cortez S',
      'Alvez',
      'Almaz Hybrid',
      'Almaz RS 2023',
      'Almaz RS',
      'Formo Max',
    ],
    'Lamborghini': [
      'Aventador',
      'Huracan',
      'Urus',
    ],
    'Ferrari': [
      'SF90 Stradale',
      'F8 Spider',
      'F8 Tributo',
      '296 GTS',
      'Roma',
      '812 GTS',
      'SF90 Spider',
      '296 GTB',
      'Portofino M',
    ],
    'Mazda': [
      'Mazda 2',
      'Mazda CX3',
      'Mazda 3 Hatchback',
      'Mazda CX-8',
      'Mazda CX-30',
      'Mazda CX 5',
      'Mazda CX 9',
      'Mazda MX 5 RF',
      'Mazda 3 Sedan',
      'Mazda 6 Sedan',
      'Mazda 2 Sedan',
      'Mazda CX-60',
      'Mazda 6 Estate',
    ],
    'BMW': [
      'BMW X5',
      'BMW iX',
      'BMW X1',
      'BMW X4',
      'BMW X7',
      'BMW X6',
      'BMW X3 M',
      'BMW X4 M',
      'BMW XM',
    ],
    'Volkswagen': [
      'Polo',
      'Tiguan Allspace',
      'T-Cross',
      'Golf GTI',
    ],
    'Jeep': [
      'Jeep Wrangler',
      'Jeep Compass',
      'Jeep Gladiator',
    ],
    'Audi': [
      'Q5',
      'Q8',
      'Q3 Sportback',
      'Q3',
      'Q7',
      'A6',
      'A8 L',
      'A7',
      'A5 Sportback',
      'TT Coupe',
      'R8',
      'A5',
      'TTS Coupe',
      'RS5',
      'RS 4 Avant',
    ],
    'Ford': [
      'Everest',
      'Ranger',
      'Ranger Raptor',
    ],
    'Peugeot ': [
      '3008',
      '5008',
      '2008',
    ],
    'Nissan': [
      'Livina',
      'Magnite',
      'X Trail',
      'Serena',
      'Kicks e-Power',
    ],
    'Volvo': [
      'XC90',
      'XC40',
      'XC60',
    ],
    'Lexus': [
      'RX',
      'LM',
      'UX',
      'LX',
      'NX',
      'ES',
      'LS',
      'LC',
    ],
    'Isuzu': [
      'Traga',
      'MuX',
      'D Max',
    ],
    'Suzuki Car': [
      'XL7',
      'Ertiga',
      'Carry',
      'S-Presso',
      'Jimny',
      'SX4 S Cross',
      'Grand Vitara',
      'Ignis',
      'Baleno',
      'APV Arena',
      'Ertiga Smart Hybrid',
    ],
    'Mercedes-Benz': [
      'C-Class Sedan',
      'S-Class',
      'E-Class',
      'A-Class Sedan',
      'EQS',
      'EQE',
      'Maybach S-Class',
      'GLA',
      'A-Class',
      'V-Class',
    ],
    'Mini': [
      'Countryman',
      '3 Door',
      '5 Door',
      'Clubman',
      'Convertible',
    ],
    'Renault': [
      'KWID',
      'Triber',
      'Kiger',
    ],
    'Tesla': [
      'Model X',
      'Model S',
      'Model 3',
    ],
    'Jaguar': [
      'XF',
      'F Type',
      'F PACE',
      'E-PACE',
    ],
    'KIA ': [
      'Sonet',
      'Seltos',
      'Grand Carnival',
      'Carens',
    ],
    // MOTOR,MOTOR,MOTOR,MOTOR,MOTOR,MOTOR,MOTOR,MOTOR,MOTOR,MOTOR,MOTOR
    'Honda': [
      'Beat',
      'Scoopy',
    ],
    'Yamaha': [
      'NMAX',
      'Jupiter',
    ],
    'Suzuki': [
      'Satria FU',
      'Burgman Street',
      'GSX',
      'NEX',
      'Address',
      'V-Strom',
      'Avenis',
      'Gixxer',
    ],
    'Kawasaki': [
      'Ninja',
      'W',
      'KLX',
      'D-Tracker',
      'Z',
      'Versys',
      'Vulcan',
    ],
    'TVS Motor': [
      'Apache',
      'Max',
      'Callisto',
      'Ntorq',
      'Dazz',
      'Neo',
      'Rockz',
      'Kargo',
      'Ronim',
    ],
    'Viar': [
      'Akasha',
      'Caraka',
      'C2',
      'Crossx',
      'Karya',
      'N1',
      'N2',
      'New Q1',
      'Razor',
      'Re',
      'U1',
      'Uno',
      'V2',
    ],
    'Benelli': [
      'Motobi',
      'Patagonia eagle',
      'TNT',
      'New Caffereno',
      'X'
          'Zafferano',
      'panarea',
      'Dong',
      'Leoncino',
      'Imperiale',
    ],
    'KTM': [
      'RC',
      'Duke',
      'Super adventure',
    ],
  };
  Map<String, List<String>> TipeOptions = {
    //MOBIL
    // HYUNDAI HYUNDAI HYUNDAI HYUNDAI HYUNDAI HYUNDAI HYUNDAI HYUNDAI HYUNDAI
    'Palisade': [
      'PALISADE D 2.2 AT Signature',
      'PALISADE D 2.2 AT Signature AWD',
      'PALISADE D 2.2 AT Prime'
    ],
    'Creta': [
      'CRETA Dynamic Black Edition',
      'CRETA Active MT 6-speed',
      'CRETA Trend MT 6-speed',
      'CRETA Trend IVT',
      'CRETA Style IVT',
      'CRETA Prime IVT',
    ],
    'Santa Fe': [
      'SANTA FE G 2.5 6AT Style',
      'SANTA FE G 2.5 6AT Signature',
      'SANTA FE D 2.2 8DCT Signature',
      'SANTA FE D 2.2 8DCT Style',
      'SANTA FE D 2.2 8DCT Style',
      'SANTA FE D 2.2 8DCT Prime',
    ],
    'Ioniq': [
      'Ioniq 6 Signature',
      'Ioniq 5 Prime - Standard Range',
      'Ioniq 5 Prime - Long Range',
      'Ioniq 5 Signature - Standard Range',
      'Ioniq 5 Signature - Long Range',
    ],
    'Stargazer': [
      'Stargazer Active IVT',
      'Stargazer Active MT',
      'Stargazer Essential IVT',
      'Stargazer Essential MT',
      'Stargazer Style IVT',
      'Stargazer Prime IVT',
    ],
    'Staria': [
      'Staria Signature 9',
      'Staria Signature 7',
    ],
    'Stargazer X': [
      'Stargaze X Style 1.5 IVT',
      'Stargaze X Prime 1.5 IVT',
    ],
    //TOYOTA TOYOTA TOYOTA TOYOTA TOYOTA TOYOTA TOYOTA TOYOTA TOYOTA TOYOTA TOYOTA
    'Alphard': [
      'Alphard 2.5 X Type',
      'Alphard 2.5 G Type',
      'Alphard 2.5 HEV Type',
    ],
    'Kijang Innova': [
      'Kijang Innova Zenix HEV',
      'Kijang Innova Zenix',
      'Kijang Innova G Type',
    ],
    'Voxy': ['Voxy 2.0 CVT'],
    'Avanza': [
      'Avanza E Type',
      'Avanza G Type',
    ],
    'Veloz': [
      'Veloz MT Type',
      'Veloz CVT Type',
    ],
    'Calya': [
      'Calya G Type',
      'Calya E Type',
    ],
    // DAIHATSU DAIHATSU DAIHATSU DAIHATSU DAIHATSU DAIHATSU DAIHATSU DAIHATSU DAIHATSU
    'Rocky': [
      'ROCKY 1.0 R',
      'ROCKY 1.2 M',
      'ROCKY 1.2 X',
    ],
    'Terios': [
      'Terios R',
      'Terios X',
    ],
    'Sirion': [
      'Sirion X',
      'Sirion R',
    ],
    'Luxio': [
      'Luxio 1.5 D',
      'Luxio 1.5 X',
    ],
    'Ayla': [
      'Ayla 1.0 M',
      'Ayla 1.0 X',
      'Ayla 1.2 R',
    ],
    'Granmax': [
      'Pick Up - PU AC PS 1.5',
      'Pick Up - PU 1.3',
      'Pick Up - PU 1.5',
      'Mini Bus - 1.5 D PS',
      'Mini Bus - 1.3 D FF',
      'Mini Bus - 1.3 D FH',
      'Blind Van - 1.3 AC',
    ],
    'Xenia': [
      'Xenia 1.3 R',
      'Xenia 1.3 M',
      'Xenia 1.3 X',
      'Xenia 1.5 R',
    ],
    'Sigra': [
      'Sigra 1.2 R',
      'Sigra 1.2 X',
      'Sigra 1.0 D',
      'Sigra 1.0 M',
    ],
    //HONDA CAR HONDA CAR HONDA CAR HONDA CAR HONDA CAR HONDA CAR HONDA CAR HONDA CAR
    'WR-V': [
      'RS Type',
      'E Type',
    ],
    'BR-V': [
      'S Type',
      'E Type',
      'Prestige Type',
    ],
    'Brio': [
      'RS Type',
      'S Type',
      'E Type',
    ],
    'Accord': ['Accord'],
    'Mobilio': ['S Type'],
    'City': [
      'City Sedan Type',
      'Hatchback RS Type',
    ],
    'HR-V': [
      'RS Type',
      'S Type',
      'E Type',
      'SE Type',
    ],
    'CR-V': [
      '2.0 RS Type',
      '1.5 Turbo',
    ],
    'Civic': ['Civic RS Type'],
    //MITSUBISHI MITSUBISHI MITSUBISHI MITSUBISHI MITSUBISHI MITSUBISHI MITSUBISHI MITSUBISHI
    'Xpander': [
      'Xpander Ultimate CVT',
      'Xpander Sport M/T',
      'Xpander GLS CVT',
      'Xpander GLS M/T',
      'Xpander Exceed CVT',
      'Xpander Exceed M/T',
      'Xpander Sport CVT',
    ],
    'Xpander Cross': [
      'Xpander Cross MT',
      'Xpander Cross Premium CVT',
    ],
    'Pajero Sport': [
      'Dakar Ultimate AT 4x2',
      'Dakar Ultimate AT 4x4',
      'Exceed MT 4x2',
      'GLX MT 4x4',
      'Exceed AT 4x2',
      'Dakar AT 4x2',
    ],
    'XForce': [
      'XForce Exceed CVT',
      'XForce Ultimate CVT',
    ],
    'Outlander PHEV': [
      'Outlander PHEV 2.4L',
    ],
    'L300': [
      'L300 Pickup Flatbed',
      'L300 Cab & ChasissRp',
    ],
    'Triton': [
      'Ultimate AT Double Cab 4WD',
      'HDX MT Single Cab 4WD',
      'HDX MT Double Cab 4WD',
      'GLS MT Double Cab 4WD',
      'Exceed MT Double Cab 4WD',
      'GLX MT Single Cab 2WD'
    ],
    //WULING WULING WULING WULING WULING WULING WULING WULING
    'Formo': [
      '1.2 Standard 5-Seat',
      '1.2 Standard 8-Seat',
      '1.2 BV',
    ],
    'Confero': ['1.5 MT Double Blower'],
    'Confero S': [
      'S 1.5 L',
      'S 1.5 C',
      'S 1.5 ACT',
    ],
    'Cortez': [
      'EX 1.5T Lux',
      'CE 1.5T Lux',
    ],
    'Cortez S': [
      'S 1.5T MT Lux',
      'S 1.5T CVT Lux',
    ],
    'Alvez': ['EX', 'SE', 'CE'],
    'Almaz Hybrid': ['2.0L'],
    'Almaz RS 2023': [
      '1.5T SE',
      '1.5T EX',
      '1.5T Pro',
      '2.0L Pro Hybrid',
    ],
    'Almaz RS': ['1.5L Pro', '1.5L EX 7 Seater'],
    'Formo Max': [
      'Max AC',
      'Max Standard',
    ],
    //LAMBORGHINI LAMBORGHINI LAMBORGHINI LAMBORGHINI LAMBORGHINI LAMBORGHINI LAMBORGHINI LAMBORGHINI
    'Aventador': [
      'LP 750-4 SUPERVELOCE ROADSTER',
      'Lp 700-4 Roadster',
      'Lp 700-4',
      'LP 750-4 Superveloce',
    ],
    'Huracan': [
      'LP 610-4',
      'Lp 620-2 Super Trofeo',
    ],
    'Urus': ['Urus 4.0L'],
    //FERRARI FERRARI FERRARI FERRARI FERRARI FERRARI FERRARI FERRARI
    'SF90 Stradale': ['4.0L'],
    'F8 Spider': ['3.9L V8'],
    'F8 Tributo': ['3.9L'],
    '296 GTS': ['3.0L'],
    'Roma': ['3.9L V8'],
    '812 GTS': ['6.5L'],
    'SF90 Spider': ['4.0L'],
    '296 GTB': ['3.0L'],
    'Portofino M': ['3.9L V8'],
    //MAZDA MAZDA MAZDA MAZDA MAZDA MAZDA MAZDA MAZDA
    'Mazda 2': ['GT AT'],
    'Mazda CX3': ['1.5L Sport', 'Pro'],
    'Mazda 3 Hatchback': ['Skyactive-G 2.0'],
    'Mazda CX-8': ['CX-8 Elite'],
    'Mazda CX-30': ['CX-30 GT'],
    'Mazda CX 5': ['CX 5 Elite', 'CX 5 2.5L AWD', 'CX 5 Kuro Edition'],
    'Mazda CX 9': ['CX 9 AWD', 'CX 9 2WD', 'CX 9 Kuro Edition'],
    'Mazda MX 5 RF': [
      'MX 5 RF AT',
      'MX 5 RF MT',
    ],
    'Mazda 3 Sedan': ['Skyactive-G 2.0'],
    'Mazda 6 Sedan': [
      '20th Anniversary',
      'Elite Sedan',
    ],
    'Mazda 2 Sedan': ['1.5L AT'],
    'Mazda CX-60': ['Elite AWD', 'Kuro AWD'],
    'Mazda 6 Estate': ['Elite', '20th Anniversary'],
    //BMW BMW BMW BMW BMW BMW BMW BMW
    'BMW X5': ['xDrive40i M Sport'],
    'BMW iX': ['xDrive 40 Sport'],
    'BMW X1': ['sDrive18i xLine'],
    'BMW X4': ['xDrive30i M Sport'],
    'BMW X7': ['xDrive40i M Sport'],
    'BMW X6': ['xDrive40i M Sport'],
    'BMW X3 M': ['M Competition'],
    'BMW X4 M': ['M Competition'],
    'BMW XM': ['.4L PHEV'],
    //VOLKSWAGEN VOLKSWAGEN VOLKSWAGEN VOLKSWAGEN VOLKSWAGEN VOLKSWAGEN VOLKSWAGEN VOLKSWAGEN
    'Polo': ['1.2L TSI'],
    'Tiguan Allspace': ['1.4L TSI'],
    'T-Cross': ['Dynamic Line'],
    'Golf GTI': ['2.0L TSI'],
    //JEEP JEEP JEEP JEEP JEEP JEEP JEEP JEEP
    'Jeep Wrangler': [
      'Rubicon 2-Door',
      'Sahara 4-Door Unlimited',
      'Rubicon 4-Door Unlimited',
    ],
    'Jeep Compass': ['Limited'],
    'Jeep Gladiator': ['Rubicon'],
    //Audi Audi Audi Audi Audi Audi Audi Audi
    'Q5': ['2.0 TFSI Quattro'],
    'Q8': ['3.0L TFSI Quattro'],
    'Q3 Sportback': ['2.0L TFSI'],
    'Q3': ['1.4 TFSI'],
    'Q7': ['3.0 TFSI Quattro'],
    'A6': ['1.8 TFSI'],
    'A8 L': ['3.0 TFSI Quattro'],
    'A7': ['3.0L T FSI Quattro Sportback'],
    'A5 Sportback': ['2.0 TFSI'],
    'TT Coupe': ['2.0 TFSI'],
    'R8': ['Coupe 5.2 V10', 'Audi R8 Coupe 5.2 V10 Plus'],
    'A5': ['Coupe 2.0 TFSI Quattro'],
    'TTS Coupe': ['2.0 TFSI Quattro'],
    'RS5': ['2.9 TFSI Quattro'],
    'RS 4 Avant': ['2.9L TFSI'],
    //Ford Ford Ford Ford Ford Ford Ford Ford
    'Everest': [
      '2.0 XLT 4X4 10 AT',
      '2.0 Titanium 4X4 10 AT',
    ],
    'Ranger': [
      '2.0 Base DC 4X4 6MT',
      '2.0 Wildtrak DC 4X4 10 AT',
      '2.0 XLT DC 4X4 10 AT',
    ],
    'Ranger Raptor': ['2.0L DC 4X4 10AT'],
    //Peugeot Peugeot Peugeot Peugeot Peugeot Peugeot Peugeot Peugeot
    '3008': ['3008 Allure Plus', '3008 Active'],
    '5008': ['5008 Active', '5008 Allure Plus'],
    '2008': ['2008 1.2L Puretech'],
    //Nissan Nissan Nissan Nissan Nissan Nissan Nissan Nissan
    'Livina': ['EL MT', 'VL AT', 'VE AT'],
    'Magnite': ['Upper MT', 'Upper CVT', 'Premium CVT', 'Premium MT'],
    'X Trail': ['VL'],
    'Serena': ['Highway Star'],
    'Kicks e-Power': ['1.2L'],
    //Volvo Volvo Volvo Volvo Volvo Volvo Volvo Volvo
    'XC90': ['XC90 PHEV'],
    'XC40': ['XC40 PHEV'],
    'XC60': ['XC60 PHEV'],
    //Lexus Lexus Lexus Lexus Lexus Lexus Lexus Lexus
    'RX': ['350h Luxury', '350 Luxury', '450h+ Luxury'],
    'LM': ['350 (4-Seater)', '350 (7-Seater)'],
    'UX': ['250h Luxury', '250h F Sport'],
    'LX': ['600 VIP', '600'],
    'NX': ['250 Luxury', '350h F Sport', '350h Luxury'],
    'ES': ['300h Ultra Luxury'],
    'LS': ['500h F Sport', '500h Executive'],
    'LC': ['500'],
    //Isuzu Isuzu Isuzu Isuzu Isuzu Isuzu Isuzu Isuzu
    'Traga': [
      'Pick Up (FD)',
      'Blind Van',
      'Box Aluminium',
    ],
    'MuX': ['4x4 AT'],
    'D Max': ['Rodeo MT', 'DC MT', 'SC MT'],
    //Suzuki Car Suzuki Car Suzuki Car Suzuki Car Suzuki Car Suzuki Car Suzuki Car Suzuki Car
    'XL7': [
      'Hybrid Alpha AT',
      'Hybrid Alpha MT',
      'Hybrid Beta AT',
      'Hybrid Beta mT',
      'Zeta AT',
      'Zeta MT',
    ],
    'Ertiga': [
      'GA MT',
      'GL AT',
      'GL MT',
    ],
    'Carry': [
      'Wide Deck',
      'Flat Deck',
      'Wide Deck AC/PS',
      'Flat Deck AC/PS',
    ],
    'S-Presso': ['1.0L AGS', '1.0L MT'],
    'Jimny': [
      'Two Tone AT',
      'Two Tone MT',
      'Single Tone AT',
      'Single Tone MT',
    ],
    'SX4 S Cross': ['AT'],
    'Grand Vitara': ['GX', 'GL'],
    'Ignis': ['GX MT', 'GX AGS'],
    'Baleno': ['AT', 'MT'],
    'APV Arena': [
      'Blind Van',
      'SGX MT',
      'GX MT',
      'GL MT',
      'GA MT',
    ],
    'Ertiga Smart Hybrid': [
      'GX MT',
      'SS AT',
      'SS MT',
      'GX AT',
    ],
    //Mercedes-Benz Mercedes-Benz Mercedes-Benz Mercedes-Benz Mercedes-Benz Mercedes-Benz Mercedes-Benz Mercedes-Benz
    'C-Class Sedan': [
      'C-Class Sedan C 300 AMG Line',
      'C-Class Sedan C 200 Avantgarde Line',
    ],
    'S-Class': ['450 4Matic Luxury'],
    'E-Class': [
      'E 300 AMG Line',
      'E 200 Avantgarde Line',
    ],
    'A-Class Sedan': [
      'AMG A 35 4MATIC',
      'A200 Progressive Line',
    ],
    'EQS': ['450+ Electric Art Line', '450+ AMG Line', '450+ Edition One'],
    'EQE': ['350+ Electric Art Line'],
    'Maybach S-Class': ['Maybach S 580 4Matic+'],
    'GLA': ['200 AMG Line', 'AMG 35 4Matic'],
    'A-Class': ['A 45 S 4Matic+'],
    'V-Class': ['V 250 Avantgarde Line'],
    //Mini Mini Mini Mini Mini Mini Mini Mini
    'Countryman': [
      'Copper S',
      'Copper',
      'John Cooper Works',
    ],
    '3 Door': [
      '3 Door Cooper S',
      '3 Door Cooper',
      '3 Door Resolute Edition',
      '3 Door John Cooper Works',
    ],
    '5 Door': [
      '5 Door Cooper',
      '5 Door Resolute Edition',
      '5 Door Cooper S',
    ],
    'Clubman': [
      'Clubman Cooper',
      'Clubman Cooper S',
      'Clubman Untold Edition',
      'Clubman John Cooper Works',
    ],
    'Convertible': [
      'Convertible John Cooper Works',
      'Convertible Copper S',
      'Convertible Copper',
      'Convertible Seaside Edition',
      'Convertible Resolute Edition',
    ],
    //Renault Renault Renault Renault Renault Renault Renault Renault
    'KWID': [
      'Climber',
    ],
    'Triber': ['RXT MT', 'RXL MT', 'RXZ AMT'],
    'Kiger': ['CVT'],
    //Tesla Tesla Tesla Tesla Tesla Tesla Tesla Tesla
    'Model X': [
      'Model X Plaid',
      'Model X Long Range',
    ],
    'Model S': ['Model S Long Range', 'Model S Plaid'],
    'Model 3': [
      'Model 3 Performance',
      'Model 3 Long Range',
      'Model 3 Standard Plus'
    ],
    //Jaguar Jaguar Jaguar Jaguar Jaguar Jaguar Jaguar Jaguar
    'XF': ['2.0 HSE'],
    'F Type': ['2.0 R-Dynamic'],
    'F PACE': ['3.0 SE'],
    'E-PACE': ['P250'],
    //KIA KIA KIA KIA KIA KIA KIA KIA
    'Sonet': [
      'Dynamic iVT',
      'Smart MT',
      'Standard MT',
      'Premiere iVT',
      'Smart iVT',
      'Active MT',
    ],
    'Seltos': [
      'EX Plus',
      'EX',
      'E',
      'GT Line',
    ],
    'Grand Carnival': [
      'Premiere',
      'Dynamic',
    ],
    'Carens': ['1.5L', '1.4L'],

    // MOTOR
    'Beat': [
      'Beat 125',
      'Beat 150',
    ],
    'Scoopy': [
      'Scoopy 125',
      'Scoopy 150',
    ],
    'NMAX': [
      'NMAX Type A',
      'NMAX Type B',
    ],
    'Jupiter': [
      'Jupiter MX',
      'Jupiter Z',
    ],
    'Ninja': [
      'Ninja 250',
      'Ninja 250SL',
      'Ninja ZX-25',
      'Ninja ZX-6R',
      'Ninja ZX-10R',
      'Ninja H2',
      'Ninja 250 ABS',
    ],
    'W': [
      'W175 SE',
      'W175 Cafe',
      'W175 TR',
      'W250',
      'W800',
      'W800 Cafe',
    ],
    'KLX': [
      'KLX 150G',
      'KLX 150L',
      'KLX 150BF',
      'KLX 230',
      'KLX 250',
      'KLX 150 SE',
    ],
    'D-Tracker': [
      'D-Tracker 150 STD',
      'D-Tracker 150 SE',
      'D-Tracker X 250',
    ],
    'Z': [
      'Z125',
      'Z250',
      'Z900 RS',
      'Z900 RS Cafe',
      'Z1000',
    ],
    'Versys': [
      'Versys X 250',
      'Versys 650',
      'Versys 1000',
    ],
    'Vulcan': [
      'Vulcan S',
      'Vulcan S SE',
    ],
    'Apache': [
      'Apache 200',
    ],
    'Max': [
      'MAX 125',
    ],
    'Callisto': [
      'Callisto Intelligo',
    ],
    'Ntorq': [
      'Ntorq 125 Race XP',
      'Ntorq 125 Fi',
    ],
    'Dazz': [
      'Dazz F1',
    ],
    'Neo': [
      'Neo XR',
    ],
    'Akasha': [
      'Akasha 1',
    ],
    'Crossx': [
      'Crossx 70 MT',
      'Crossx 100 MT',
      'Crossx 150',
    ],
    'Karya': [
      'Karya Bit',
      'Karya 150',
      'Karya 150 Box',
      'Karya 150 BHS',
      'Karya 150 BFS',
      'Karya 150 RMDT',
    ],
    'Razor': [
      'Razor 100 SP',
      'Razor 150 UT',
      'Razor 200 RZM',
    ],
    'Re': [
      'Re 3',
    ],
    'Motobi': [
      'Motobi 152',
      'Motobi 200 WS/ EFI ',
      'Motobi 200 EVO',
    ],
    'Patagonia eagle': [
      'Patagonia Eagle 250',
      'Patagonia Eagle 250 EFI ',
    ],
    'TNT': [
      'TNT 135',
      'TNT 249S',
      'TNT 600',
      'TNT 1130 ',
      'TNT 899 ',
      'TNT 15',
      'TNT 25',
    ],
    'New Caffereno': [
      'New Caffereno 150',
    ],
    'X': [
      'X 150',
    ],
    'Zafferano': [
      'Zaffereno 250',
    ],
    'Leoncino': [
      'Leoncino 500',
    ],
    'Imperiale': [
      'Imperiale',
    ],
    'RC': ['RC 390', 'RC 250', 'RC 200', ''],
    'Duke': [
      'Duke 390',
      'Duke 250',
      'Duke 200',
      '1290 Super Duke GT',
      'Duke 790',
      '1290 Super Duke R',
      'Duke 690',
    ],
    'Super Adventure': [
      '1290 Super Adventure S',
      '1090 Adventure R',
      '1090 Adventure',
    ],
  };
}
